### ISSUE TITLE
Can't call the server with 2-way TLS based on trusting CA authority - javax.net.ssl.SSLHandshakeException: None of the TrustManagers trust this server certificate chain

### ISSUE THREAD

**Issue by EugeneBy** [Hakky54/mutual-tls-ssl#55]
After going through the instructions for setting up two way TLS bases on [trusting the certificate authority]( https://github.com/Hakky54/mutual-tls-ssl#two-way-tls-based-on-trusting-the-certificate-authority), when I run the tests I get the following exception:

```
javax.net.ssl.SSLHandshakeException: None of the TrustManagers trust this server certificate chain

	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
       <...>
	at nl.altindag.client.service.ApacheHttpClientService.executeRequest(ApacheHttpClientService.java:32)
	at nl.altindag.client.stepdefs.HelloStepDefs.iSayHelloWithClient(HelloStepDefs.java:47)
	at ✽.I say hello with "Apache HttpClient"(file:///Users/eugeneh/Development/mutual-tls-ssl/client/src/test/resources/features/Hello.feature:6)
Caused by: java.security.cert.CertificateException: None of the TrustManagers trust this server certificate chain
	at nl.altindag.sslcontext.trustmanager.CompositeX509TrustManager.checkServerTrusted(CompositeX509TrustManager.java:86)
	at io.netty.handler.ssl.util.X509TrustManagerWrapper.checkServerTrusted(X509TrustManagerWrapper.java:63)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:629)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:464)
      <...>
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

Any ideas what I'm doing wrong?

**Comment by Hakky54** [comment]
Hi @EugeneBy 

It looks like the client somehow does not trust the server. This could mean that:
1. The root ca certificate is not present in the truststore of the client
2. There is not truststore present
3. The server certificate is not signed with the provided root-ca and therefor also not trusted by the client if the client trusts the certificate authority

So to track down the root cause I need more details. Could you push your changes to your own repository, which you forked from this one?

**Comment by EugeneBy** [comment]
Hi @Hakky54,

I've pushed the changes: https://github.com/EugeneBy/mutual-tls-ssl/pull/2

**Comment by Hakky54** [comment]
Great, I just pulled your latest commit. When I start the App.java and afterwards ClientRunnerIT.java it passes. If I run maven clean install from the root directory is also pases. I also validated your identities and truststores of both the server and the client. The setup looks good and the keystores are loaded. Do you still have uncommitted local changes?

**Comment by Hakky54** [comment]
I also made a video of the test your repo, see here: https://youtu.be/K5GHCfR-wNY

**Comment by EugeneBy** [comment]
Hey @Hakky54,
Thanks for investigating this. I'll try to follow the steps, you performed in the video and inspect the state of the truststore/keystore on both client and server side.
I believe, the problem could be caused by the version of JDK I'm running - it's possible that it would reject any certificate, that is not signed by my organization's CA.

**Comment by Hakky54** [comment]
Could you try with openjdk 11 or oracle jdk 11?

**Comment by Hakky54** [comment]
Hi again @EugeneBy

I got the same  SSLHandshakeException exception when using the Oracle JDK and especially the following exception even deeper in the stacktrace: `ValidatorException: TrustAnchor with subject is not a CA certificate`. The issue was that the root-ca provided in this project was created without the following property: `-ext bc:c`. So it was basically not a really valid ca because of missing that property.

**Comment by Hakky54** [comment]
> TrustAnchor with subject is not a CA certificate

For anyone finding out this page because they have the error:`TrustAnchor with subject is not a CA certificate`
I posted at stackoverflow more detailed steps with explanation for the one who don't want to follow the full tutorial but only want to resolve this exception, see here for the stackoverflow answer: https://stackoverflow.com/a/69416217/6777695
